POST http://localhost:8080/users/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin1234"
}

###
POST http://localhost:8080/guides
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZWZiY2FhNDk0OGJlMjZiMDdjNDNjIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzczODcxOCwiZXhwIjoxNjkzODI1MTE4fQ.6jOJGi38gisp-eBItZQUS9N64SbkiZbHxFjnvj_1HbU
Content-Type: application/json

{
    "title": "foobaz",
    "content": "bar"
}


###     
GET http://localhost:8080/guides
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZWZiY2FhNDk0OGJlMjZiMDdjNDNjIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzczODcxOCwiZXhwIjoxNjkzODI1MTE4fQ.6jOJGi38gisp-eBItZQUS9N64SbkiZbHxFjnvj_1HbU

###     
GET http://localhost:8080/guides/64eefbcaa4948be26b07c442
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZWZiY2FhNDk0OGJlMjZiMDdjNDNjIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzczODcxOCwiZXhwIjoxNjkzODI1MTE4fQ.6jOJGi38gisp-eBItZQUS9N64SbkiZbHxFjnvj_1HbU

###
PATCH http://localhost:8080/guides/64eefbcaa4948be26b07c441
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZWZiY2FhNDk0OGJlMjZiMDdjNDNjIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzczODcxOCwiZXhwIjoxNjkzODI1MTE4fQ.6jOJGi38gisp-eBItZQUS9N64SbkiZbHxFjnvj_1HbU
Content-Type: application/json

{
    "title": "Oylik maoshni sir saqlash bo'yicha tartib",
    "notify": true
}


###     
DELETE  http://localhost:8080/guides/64ee1484fbbf7cb856e4d345
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZWZiY2FhNDk0OGJlMjZiMDdjNDNjIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzczODcxOCwiZXhwIjoxNjkzODI1MTE4fQ.6jOJGi38gisp-eBItZQUS9N64SbkiZbHxFjnvj_1HbU
